client_config_backend: settings
client_config:
  client_id: YOUR DRIVE API Client ID (Type Desktop Application)
  client_secret: YOUR DRIVE API CLIENT SECRET

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
 
oauth_scope:
  - https://www.googleapis.com/auth/drive
